import React from "react";
import Head from "next/head";
import Image from "next/image";
import {
  AppBar,
  Box,
  Button,
  Container,
  IconButton,
  Menu,
  MenuItem,
  Toolbar,
  Typography,
} from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Easy Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Stickied NavBar */}
      <AppBar
        sx={{
          backgroundColor: "white",
        }}
        position="sticky"
      >
        <Toolbar>
          <Box
            sx={{
              pl: 6,
            }}
          >
            <Image src="/logo.svg" alt="logo" width={100} height={15} />
          </Box>

          <Box
            sx={{
              color: "#a9a9a9",
            }}
          >
            <Button color="inherit">Home</Button>
            <Button color="inherit">About</Button>
            <Button color="inherit">Contact</Button>
            <Button color="inherit">Blog</Button>
            <Button color="inherit">Careers</Button>
          </Box>
          <Box>
            <Button color="inherit">Request Invite</Button>
          </Box>
        </Toolbar>
      </AppBar>

      {/* Header */}
      <Container
        sx={{
          height: "90vh",
        }}
      >
        <Box>Hello</Box>
      </Container>
    </>
  );
}
